### ISSUE TITLE
Startup on OS X

### ISSUE THREAD

**Issue by jareware** [cpesch/RouteConverter#40]
I'm having trouble starting the latest version on OS X.

If I just double-click the app after download I get a popup saying "JRELoadError".

If I run it from the CLI:
```
$ java -jar RouteConverterMac.app/Contents/Java/RouteConverterMac.jar
Jul 26 13:46:14 FL627-3 java[61698] <Error>: The function ‘CGContextErase’ is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance.
Exception in thread "main" java.lang.UnsupportedClassVersionError: slash/navigation/converter/gui/RouteConverter : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
```

**Comment by cpesch** [comment]
You're starting RouteConverter with Apples Java 1.6 although it is compiled for at least 1.7 (class version 51)

Please check the README
