### ISSUE TITLE
Class loading Problem with duplicate MapSelector#$$$getFont$$$

### ISSUE THREAD

**Issue by lbreuss** [cpesch/RouteConverter#87]
When running the Application from within IntelliJ by running `slash.navigation.converter.gui.RouteConverterOpenSource`, some class loading problem occurs with `slash.navigation.mapview.mapsforge.MapSelector#$$$getFont$$$`
at 
```
slash.navigation.mapview.mapsforge.MapsforgeMapView#initializeMapView`, 
Line 350:         mapSelector = new MapSelector(getMapManager(), mapView);
```

```
May 03, 2024 11:42:17 PM slash.navigation.download.performer.GetPerformer download
INFO: Downloading 394701 bytes from https://api.routeconverter.com/v1/datasources/srtm1/?format=xml with ETag "134b17bdc6175aaf7f769e2e552daf37"
Exception in thread "AWT-EventQueue-0" java.lang.ClassFormatError: Duplicate method name "$$$getFont$$$" with signature "(Ljava.lang.String;IILjava.awt.Font;)Ljava.awt.Font;" in class file slash/navigation/mapview/mapsforge/MapSelector
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at slash.navigation.mapview.mapsforge.MapsforgeMapView.initializeMapView(MapsforgeMapView.java:350)
	at slash.navigation.mapview.mapsforge.MapsforgeMapView.initialize(MapsforgeMapView.java:312)
	at slash.navigation.converter.gui.RouteConverter.setMapView(RouteConverter.java:368)
	at slash.navigation.converter.gui.RouteConverter.lambda$openMapAndProfileView$7(RouteConverter.java:342)
	at java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:318)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I'm a noob regarding this IntelliJ-generated UI code. What things can I check on my end? I suppose it's a valid approach to run the application from within IntelliJ, but somehow I suspect my IntelliJ to not-so-intelligently generate another version of $$$getFont$$$ on the fly... The MapSelector.class in the RouteConverterLinuxOpenSource.jar is OK, it only contains one method $$$getFont$$$.
Gruss, Leo

checked out the latest master, a839bcdf2, 3.1-SNAPSHOT
Ubuntu 20.04.6 LTS x86_64, 
openjdk version "17.0.10" 2024-01-16
IntelliJ 2023.1, Debug Run Configuration starting `slash.navigation.converter.gui.RouteConverterOpenSource`
`mvnw clean package` worked flawlessly. 
`java -jar RouteConverterLinuxOpenSource/target/RouteConverterLinuxOpenSource.jar` works.

**Comment by lbreuss** [comment]
Found a workaround: In the IntelliJ Settings --> GUI Designer, switch to "Generate GUI into Java source code".

Is this the proper approach?

**Comment by cpesch** [comment]
Yes, this is the proper approach. I've extended the README.md
